version: "3"

services: 
    app:
        build: 
            context: .
        ports: 
            - 5000:5000
    json-server:
        image: clue/json-server
        volumes: 
            - ./public/db.json:/data/db.json
        ports: 
            - 2020:80
        restart: always